---
- name: Setup Mysql database 
  hosts: db_server
  become: yes
  tasks:
    - name: Updated apt cache
      apt:
        update_cache: yes             
        cache_valid_time: 3600
    
    - name: Install Mysql Server
      apt:
        name:
          - mysql-server
          - python3-pymysql
        state: present                 
    
    - name: Start and enable mysql
      service:
        name: mysql
        state: started                 
        enabled: yes
    
    - name: Configure MySQl to Listen on all interfaces
      lineinfile:                      
        path: /etc/mysql/mysql.conf.d/mysqld.cnf  
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'  
        backup: yes
      notify: Restart MySQL
    
    - name: Create Wordpress database
      mysql_db:                       
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Create Wordpress database user
      mysql_user:                     
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: '%'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Ensure Mysql is Listening
      wait_for:
        port: 3306
        delay: 2
            
  handlers:
    - name: Restart MySQL
      systemd:                        
        name: mysql
        state: restarted

- name: Setup Wordpress Web Server
  hosts: web_server                    
  become: yes
  tasks:
    - name: Updated apt cache
      apt:
        update_cache: yes             
        cache_valid_time: 3600         
    
    - name: Install Apache and dependencies
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - wget
          - unzip
        state: present
        
    - name: Start and enable apache
      systemd: 
        name: apache2
        state: started                 
        enabled: yes
            
    - name: Download Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
    
    - name: Extract Wordpress
      unarchive:       
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: yes
    
    - name: Remove default Apache content
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: Copy wordpress files to web root
      copy:
        src: /tmp/wordpress/
        dest: /var/www/html/
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Create wp-config.php from sample
      copy:                           
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0644'
        
    - name: Configure database name in wp-config.php
      replace: 
        path: /var/www/html/wp-config.php
        regexp: "database_name_here"
        replace: "{{ db_name }}"
    
    - name: Configure database user in wp-config.php
      replace:                        
        path: /var/www/html/wp-config.php
        regexp: "username_here"
        replace: "{{ db_user }}"
        
    - name: Configure database password in wp-config.php
      replace:
        path: /var/www/html/wp-config.php
        regexp: "password_here" 
        replace: "{{ db_password }}"
       
    - name: Configure database host in wp-config.php
      replace: 
        path: /var/www/html/wp-config.php
        regexp: "localhost"            
        replace: "{{ db_host }}"
        
    - name: Set correct permission
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes
    
    - name: Test Mysql connection from web server
      command: mysqladmin -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} ping
      register: mysql_test
      failed_when: false
      changed_when: false
    
    - name: Display connection status
      debug: 
        msg: "MySQL connection: {{ 'SUCCESS' if mysql_test.rc == 0 else 'FAILED' }}"
    
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted        
